apiVersion: v1
kind: Namespace
metadata:
  name: security
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: policy-enforcer
  namespace: security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policy-enforcer-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["crd.projectcalico.org"]
    resources: ["globalnetworkpolicies"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: policy-enforcer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: policy-enforcer-role
subjects:
  - kind: ServiceAccount
    name: policy-enforcer
    namespace: security
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-enforcer
  namespace: security
  labels:
    app: policy-enforcer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-enforcer
  template:
    metadata:
      labels:
        app: policy-enforcer
    spec:
      serviceAccountName: policy-enforcer
      containers:
        - name: policy-enforcer
          # TODO: build and push this image (we'll handle later)
          image: thereevemenezes/policy-enforcer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: HONEYPOTS_NAMESPACE
              value: "honeypots"
            - name: HONEYPOT_LABEL_SELECTOR
              value: "app=cowrie-honeypot"
