apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-honey-nginx
  namespace: honeypots
  labels:
    app: dummy-honey-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-honey-nginx
  template:
    metadata:
      labels:
        app: dummy-honey-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dummy-honey-nginx-svc
  namespace: honeypots
spec:
  selector:
    app: dummy-honey-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP 
